palavra = input("digite qual quer coisa aqui:")
print("o tipo primitivo desse valor é", type(palavra))
print("so tem espaços?", palavra.isspace())
print("é um numero?", palavra.isnumeric())
print("é alfabetico?", palavra.isalpha())
print("é alfanumerico?", palavra.isalnum())
print("esta em maiusculo?", palavra.isupper())
print("esta em minusculo?", palavra.islower())
print("esta capitalizada?", palavra.istitle())
